version: '3.8'

services:
  db:
    image: mysql:5.7.35
    restart: always
    ports:
      - ${DB}:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - rede
    environment:
        MYSQL_ROOT_PASSWORD: "root"

  phpmyadmin:
    image: phpmyadmin:5
    restart: always
    ports: 
      - "${SGBD}:80"
    networks: 
      - rede
    depends_on: 
      - db
    environment:
      PMA_HOST: "db"
      PMA_USER: "root"
      PMA_PASSWORD: "root"

volumes:
  db_data:

networks:
  rede: